### ISSUE TITLE
Trapper calculation is wrong... someone can fix it???

### ISSUE THREAD

**Issue by Krimper** [yi12345/TravianZ#133]
Hello, when I do a raid attack, everything goes well and the units are shipping prisoners, but, when I send then a normal attack troops recover, release them, but the traps that were free when the attack came in normal are automatically filled and only released that were previously occupied

**Comment by akshay9** [comment]
bro in real travian also, when you attack to release your troops sum of them dies.

**Comment by barin** [comment]
Well really the problem is with a sql warning that say something like " wrong sql 'to 5314' " or something like that, no is a problem about troops die or not. example enemy 2 prisoners and send a attack to free that prisoners of 10 units. Defender 5 traps, anything else. reports goes everything well but defender have 3 traps occuped without any troops in the traps and you get the sql error.
