### ISSUE TITLE
Hero dissapear

### ISSUE THREAD

**Issue by Shadowss** [yi12345/TravianZ#252]
When i send hero as reinforcement on another village with troops like 

GodOfWar6   GodOfWar troops
    Legionnaire Praetorian  Imperian    Equites Legati  Equites Imperatoris Equites Caesaris    Battering Ram   Fire Catapult   Senator Settler
Troops  0   0   40000   300 30000   0   262 78  0   0
Upkeep  
131854Cropper hour
Send back

After 1 day hero dissapear , not die , because i see on hero mansion just dissapear.

Any ideea ?

Example : 

Yesterday send as reinforcement from
GodOfWar (-7|5)
at village
GodOfWar6 (-42|21)
where i have hero mansion at level 10, just send as reinforcement with other offensive troops . My offensive troops not dissapear just my hero

**Comment by turkmaxi** [comment]
My hero is going to oasis for reinforcement and my hero lost.I am seeing on her mansion but It was lost... we have same problems

**Comment by IngMak** [comment]
Yes I know what happens. the function who have to add the hero do not exists, only the function for the other troop is working.

**Comment by Shadowss** [comment]
@IngMak : give me some detail on what file and on what function you reffer ? specify the function or some part of code

**Comment by IngMak** [comment]
hello..., let's go to business.
The problem is on Automation.php, function sendreinfunitsComplete()

see line 3039 to line 3049 . that code works perfectly if reinforcements are sent between villages from the same owner, but fail if you want to reinforce other players villages with the hero.

to the code in line 3039..3049:

if($data['t11'] != 0) {
if($database->getVillageField($data['from'],"owner") == $database->getVillageField($data['to'],"owner")) {
for($i=1;$i<=10;$i++) { if($data['t'.$i]>0) { $NonHeroPresent = 1; break; } }
if($NonHeroPresent == 0 && $this->getTypeLevel(37,$data['to']) > 0) {
//don't reinforce, addunit instead
$database->modifyUnit($data['to'],array("hero"),array(1),array(1));
$heroid = $database->getHero($database->getVillageField($data['from'],"owner"),1);
$database->modifyHero("wref",$data['to'],$heroid,0);
$HeroTransfer = 1;
}
}

in line 3049 I add (after "}":

else{
// hero goes to reinforce other player village
   $check = $database->getEnforce($data['to'], $data['from']);
  if (isset($check['id'])) {
      // if there are troops of the same owner hero, then hero is added to them
      $database->modifyEnforce($check['id'], "hero", 1, 1);
      }else{
      // the heroe is the only troop that reinforces
         $data['t11']=1;
         $database->addEnforce($data);
           }

```
}
```

PD: if somebody need a better explanation please email me, i love travian.

## 

Saludos,
Juan Danilo

**Comment by Shadowss** [comment]
Leave me your skype , yahoo or email. Some metod to speak with you faster in real time

**Comment by IngMak** [comment]
my e- mail is: juandanilo[arroba]uci.cu

## 

Saludos,
Juan Danilo

**Comment by Shadowss** [comment]
Sended an email to you.

**Comment by Shadowss** [comment]
Solved.
