### ISSUE TITLE
Peace system bug (return bug)

### ISSUE THREAD

**Issue by Shadowss** [yi12345/TravianZ#379]
Here is a video with bug : http://www.youtube.com/watch?v=2iS2225F-lc

**Comment by eliopinho** [comment]
this is the same thing happen's with me, bue in normal mode!
movements, or buildings too...
or sometimes, the time is the same with the server time, and counting up...

**Comment by Shadowss** [comment]
Hmmm , for me it`s only on PEACE system. I tested that 4 mounth ago , and now i remember to test again and post.

**Comment by eliopinho** [comment]
and the server enters in a very very lag mod, so much slowy...

the "strange way i found do Resolv the problem" is:

when i for example lanch an attack, movements time reach 0 and the troops reach the target, the attack still continues "on the way to the target, and the clock of the movement is the same of the time server and counting up.."

i go to rally point where i launch the attack, the server blocks (blocks when i go to dorf1 of that village or rally point of that village) but, in the rally point i copy one of the links of send back (reenforcement i have in other villages),
close the browser and open again and past the links.. when i do that automatic im going to a2b.php (and normaly the Reports appears and the problem is fixed) :(

hours and hours i spend try to back to normal, and this is the only way i found :(
